[package]
name = "odom_predictor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bno055 = "0.3.3"
embedded-hal = "0.2.7"
mint = "0.5.9"
nalgebra = "0.32.0"
rppal = "0.14.1"

